version: '3.8'

services:
  velotrace:
    build: .
    container_name: velotrace-app
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 3
